title: Austin J Ferguson
description: Just my personal site :^)
show_downloads: false
theme: jekyll-theme-minima
repository: FergusonAJ/fergusonaj.github.io
baseurl: /

minima:
# Minima date format.
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
# Generate social links in footer.
#
  social_links:
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=sqJjSc0AAAAJ" }
    - { platform: github,         user_url: "https://github.com/FergusonAJ" }
#   - { platform: twitter,        user_url: "https://twitter.com/FergusonAJ17" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/austin-ferguson-0b5953125" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
  - research.md
  - pubs.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

